name: deploy-live

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, live, nottinfra]
    env:
      VAULT_ADDR: http://vault:8200
      VAULT_READ_TOKEN: ${{ secrets.VAULT_READ_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: bash ./release/steps/build.sh live
      - run: bash ./release/steps/unit-test.sh live
      - run: bash ./release/steps/trivy.sh live
      - run: bash ./release/steps/sonar.sh live
      - run: bash ./release/steps/push.sh live
      - run: bash ./release/steps/deploy.sh live
